#YETIs Utils made by YETI
#reason for making it felt like it tbf
#plugin creation date 23-05-2024
#plugin version 3.5 - release date 02-06-24

log-time-and-date: true  #enable or disable the logging of when a warn was given
enablePlayerWarningsView: true  #enable or disable player being able to view their own warns
debug: false #for debugging does spam console when used recommended false (i dont think this even works anymore :/ )
maxWarningsBeforeBan: 0  # Set to 0 for unlimited warnings, any other number for the warning limit before ban-ip a player
enableReportFeature: true #this will enable or disable the ingame report feature so player will or wont be able to use /report


######################
# Discord Bot Settings
######################
# https://discord.com/developers/applications this is to create a new bot for your server then past its token in the discord-bot-token including the ""
# note u need the id for the text channel using devmode on discord once enabled right click the channel and a new copy id button will be available
# if you don't want to use the discord part of this plugin leave it how it is now

discord-bot-token: "YOUR_DISCORD_BOT_TOKEN"
discord-report-channel-id: "YOUR_DISCORD_REPORT_CHANNEL_ID"
discord-warning-channel-id: "YOUR_DISCORD_WARNING_CHANNEL_ID"