#YETIs Utils made by YETI
#reason for making it felt like it tbf
#creation date 23-05-2024
#

log-time-and-date: true  #enable or disable the logging of when a warn was given
enablePlayerWarningsView: true  #enable or disable player being able to view their own warns
