#YETIs Utils made by YETI
#reason for making it felt like it tbf
#plugin creation date 23-05-2024
#plugin version 3.1.1 - release date 30-05-24

log-time-and-date: true  #enable or disable the logging of when a warn was given
enablePlayerWarningsView: true  #enable or disable player being able to view their own warns
debug: false #for debugging does spam console when used recommended false 
maxWarningsBeforeBan: 0  # Set to 0 for unlimited warnings, any other number for the warning limit before ban-ip a player
enableReportFeature: true #this will enable or disable the ingame report feature so player will or wont be able to use /report