#YETIs Utils made by YETI
#reason for making it felt like it tbf
#plugin creation date 23-05-2024
#plugin version 2.6 - release date 27-05-24

log-time-and-date: true  #enable or disable the logging of when a warn was given
enablePlayerWarningsView: true  #enable or disable player being able to view their own warns
debug: false #for debugging does spam console when used recommended false
maxWarningsBeforeBan: 0  # Set to 0 for unlimited warnings, any other number for the warning limit before banning