name: YETIsUtils
version: 2.6
main: org.yetiman.yetisutils.YETIsUtils
api-version: 1.20
commands:
  adminmode:
    description: Toggles between admin and player inventory
    usage: /<command>
    permission: yetisutils.adminmode
  warn:
    description: Issues a warning to a player
    usage: /<command> <player> <reason>
    permission: yetisutils.warn
  warnings:
    description: Views warnings of a player
    usage: /<command> <player>
    permission: yetisutils.warnings
  warnmenu:
    description: Opens the warning GUI
    usage: /<command>
    permission: yetisutils.warnmenu
  warnclear:
    description: Clears a specific warning of a player
    usage: /<command> <player> <warning number>
    permission: yetisutils.warnclear
  mywarnings:
    description: Views your own warnings
    usage: /<command>
    permission: yetisutils.mywarnings
  report:
    description: Submits a report
    usage: /<command> <issue>
    permission: yetisutils.report
  reportmenu:
    description: Opens the report GUI
    usage: /<command>
    permission: yetisutils.reportmenu
  yetisutils:
    description: Reloads the plugin configuration
    usage: /<command> reload
    permission: yetisutils.reload
permissions:
  yetisutils.adminmode:
    description: Allows using the adminmode command
    default: op
  yetisutils.warn:
    description: Allows issuing warnings
    default: op
  yetisutils.warnings:
    description: Allows viewing warnings
    default: op
  yetisutils.warnmenu:
    description: Allows opening the warning GUI
    default: op
  yetisutils.warnclear:
    description: Allows clearing warnings
    default: op
  yetisutils.mywarnings:
    description: Allows viewing your own warnings
    default: true
  yetisutils.report:
    description: Allows submitting reports
    default: true
  yetisutils.reportmenu:
    description: Allows opening the report GUI
    default: op
  yetisutils.reload:
    description: Allows reloading the plugin configuration
    default: op
