name: YETIsUtils
version: 1.1
main: org.yetiman.yetisutils.YETIsUtils
api-version: 1.20
commands:
  adminmode:
    description: Toggle between admin and player inventories.
    usage: /adminmode
  warn:
    description: Warn a player.
    usage: /warn <player> <reason>
    permission: yetisutils.warn
    permission-message: You do not have permission to warn players.
  warnings:
    description: Check the number of warnings a player has.
    usage: /warnings <player>
    permission: yetisutils.warnings
    permission-message: You do not have permission to check warnings.
  warninggui:
    description: Open the warnings GUI.
    usage: /warninggui
    permission: yetisutils.warninggui
    permission-message: You do not have permission to open the warnings GUI.
permissions:
  yetisutils.warn:
    description: Allows the player to warn others.
    default: op
  yetisutils.warnings:
    description: Allows the player to check warnings.
    default: op
  yetisutils.warninggui:
    description: Allows the player to open the warnings GUI.
    default: op
