name: YETIsUtils
main: org.yetiman.yetisutils.YETIsUtils
version: 2.2
description: A versatile Minecraft plugin providing admin utilities and a player warning system.
author: YET1MAN
commands:
  adminmode:
    description: Toggles admin mode.
    permission: yetisutils.adminmode
  warn:
    description: Warns a player.
    usage: /warn <player> <reason>
    permission: yetisutils.warn
  warnings:
    description: Shows warnings of a player.
    permission: yetisutils.warnings
  warnmenu:
    description: Opens the warnings menu.
    permission: yetisutils.warnmenu
  warnclear:
    description: Clears a specific warning of a player.
    usage: /warnclear <player> <warning number>
    permission: yetisutils.warnclear
  mywarnings:
    description: Shows your own warnings.
    usage: /mywarnings
    permission: yetisutils.mywarnings
permissions:
  yetisutils.adminmode:
    description: Allows the use of /adminmode command.
    default: op
  yetisutils.warn:
    description: Allows the use of /warn command.
    default: op
  yetisutils.warnings:
    description: Allows the use of /warnings command.
    default: op
  yetisutils.warnmenu:
    description: Allows the use of /warnmenu command.
    default: op
  yetisutils.warnclear:
    description: Allows the use of /warnclear command.
    default: op
  yetisutils.mywarnings:
    description: Allows the use of /mywarnings command.
    default: true
